Make LaunchAtLogin get correctly notarized by Apple when building with configurations named other than `Release`
sindresorhus/LaunchAtLogin pull request #52
Opened 2020-12-14 18:47 UTC by rameerez

`LaunchAtLogin` made the assumption that production releases were built using a configuration named `Release`, but it's often helpful to use other configuration names, like `Release-MAS`. This prevented the copy helper script from removing the `LaunchAtLogin_LaunchAtLogin.bundle` on such releases, making the notarization process fail.

Made the script remove the bundle on all builds except those using a configuration named explicitly `Debug` and added the new assumption to the Readme FAQ.

This should fix #50.

2020-12-20 06:01 UTC, sindresorhus commented
> I wonder if it's possible to detect if the current configuration is "release build type" without matching on the name.

Any thoughts on this? (From the issue). Would be a much better solution if possible.

2020-12-20 06:02 UTC, sindresorhus requested changes

2020-12-20 06:02 UTC, sindresorhus commented on Sources/LaunchAtLogin/copy-helper-swiftpm.sh
> +	codesign --force --entitlements="$package_resources_path/LaunchAtLogin.entitlements" --deep -o runtime --sign="$EXPANDED_CODE_SIGN_IDENTITY_NAME" "$login_helper_path"
Use the long-flag like before.

2021-01-14 12:38 UTC, onmyway133 commented on readme.md
> +This framework makes the assumption that your debug configuration is named `Debug`. If you are ussing different configuration names, like `Debug-MAS`, the `LaunchAtLogin_LaunchAtLogin.bundle` will ge
A little typo here `ussing`

2021-02-17 13:49 UTC, zackdotcomputer commented
Hello! I just ran into #50 as well after making a separate "Not App Store" release config for notarized distribution. Hoping we might be able to get this fixed up and merged...

Looking into the question @sindresorhus asked above about whether there was a way to switch on "debug vs. release" other than by name matching the build config, I dumped the ENV variables for release, debug, and a custom debug scheme and I think the best solution would be to use the `$GCC_PREPROCESSOR_DEFINITIONS` value which appears to include `DEBUG=1` whenever the build config is based on the default debug config (unless the developer has turned off Debug preprocessing for some reason).

There's also the `$ONLY_ACTIVE_ARCH` flag which will be `YES` for debug builds that are targeting a single arch and `NO` for release builds meant to be copied and distributed. That might be a bit more reliable though I'm not enough of a GCC expert to say 100% whether there are edge cases with this flag.

2021-02-17 13:51 UTC, zackdotcomputer commented
I guess it's good form to do your own PR rather than drive-by'ing someone else's. Will spin one up based on this one.

2021-03-20 09:17 UTC, sindresorhus commented
Closing in favor of #57

2021-03-20 09:17 UTC, closed without merging