fixed: macCatalyst
sindresorhus/LaunchAtLogin pull request #62
Opened 2021-07-13 11:32 UTC by plananderson

Added support for macCatalyst

Fixes #46

2021-07-13 15:52 UTC, sindresorhus requested changes

2021-07-13 15:52 UTC, sindresorhus commented on Sources/LaunchAtLogin/LaunchAtLogin.swift
> +			Self._SMLoginItemSetEnabled(id: id, isEnabled: newValue)
This method should only be used on Catalyst. Use a `#if` check.

2021-07-13 15:52 UTC, sindresorhus commented on Sources/LaunchAtLogin/LaunchAtLogin.swift
> +	private static func _SMLoginItemSetEnabled(id: String, isEnabled: Bool) {
This should be wrapped in an `#if` check for Catalyst. I would also move it to a private top-level function.

2021-07-13 15:52 UTC, sindresorhus commented on Sources/LaunchAtLogin/LaunchAtLogin.swift
> +		let sym = dlsym(handle, "SMLoginItemSetEnabled")
Not clear to me what's going on here. A code comment would be useful to explain how exactly this makes the macOS API available in Catalyst.

2021-07-13 15:53 UTC, sindresorhus commented
Mention in the readme that Catalyst is supported.

2021-07-13 15:53 UTC, sindresorhus commented
Have you tried this solution in a shipping app? Will Apple allow this on the App Store?

2021-10-04 07:21 UTC, closed without merging

2022-04-26 10:53 UTC, frogg commented
I am using LaunchAtLogin in Homie which is a Catalyst app: https://apps.apple.com/app/apple-store/id1533590432